### ISSUE TITLE
envsubstitute and templating inside `extraManifests` files

### ISSUE THREAD

**Issue by soostdijck** [budimanjojo/talhelper#1012]
Hello, 

I'd like to request the ability to do envsubstitute and templating inside `extraManifests` files. This is needed when creating multiple clusters using talhelper, where values are different between the clusters (for example IP ranges).

My real world use-case for this is using `extraManifests` to add node firewall manifests. For example the [talos docs gives examples](https://www.talos.dev/v1.10/talos-guides/network/ingress-firewall/) like this:
```
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
  ports:
    - 10250
  protocol: tcp
ingress:
  - subnet: $CLUSTER_SUBNET
```

In my talenv I have range like this:
```
clusterPodNets: ["10.62.40.0/21","2001:067c:baa:123:foo:c01a:0040:0000/112"]
clusterSvcNets: ["10.62.28.0/23","2001:067c:baa:123:foo:c01a:0028:0000/112"]

```

Because of the way the `ingress:` is built, prepending `- subnet:` I think I need some templating as well to make this work. Alternatively I can duplicate my clusterPodNets inside my talenv file(s) and prepend the `- subnet:` manually, but that's not very DRY
