### ISSUE TITLE
How to handle unsupported MachineConfig options in TalHelper

### ISSUE THREAD

**Issue by marcopornic** [budimanjojo/talhelper#1016]
Hi and thanks for your work!

I'm discovering TalHelper and it's a very handy tool! However, I have a few questions.

Today I have a talos patch like this:

```
cluster:
  allowSchedulingOnControlPlanes: true
  apiServer:
    admissionControl:
      - name: PodSecurity # Name is the name of the admission controller.
        configuration:
          exemptions:
            namespaces:
              - metallb-system
              - local-path-storage
              - traefik
              - haproxy
              - longhorn-system
              - postgresql
              - kubernetes-dashboard
  discovery:
    enabled: false
machine:
  install:
    image: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245:v1.9.5
  sysctls:
    vm.nr_hugepages: "1024"
  kernel:
    modules:
      - name: nvme_tcp
      - name: vfio_pci
      - name: uio_pci_generic
  registries:
    mirrors:
      "127.0.0.1:31998":
        endpoints:
          - http://10.10.205.14:31998
      "127.0.0.1:31999":
        endpoints:
          - http://10.10.205.14:31999

  features:
    imageCache:
      localEnabled: true
  time:
    disabled: true
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/local-path-provisioner
        type: bind
        source: /var/local-path-provisioner
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  files:
    - content: |
        [metrics]
          address = "0.0.0.0:11234"
      path: /etc/cri/conf.d/20-customization.part
      op: create
---
apiVersion: v1alpha1
kind: VolumeConfig
name: IMAGECACHE
provisioning:
  diskSelector:
    match: 'system_disk'
  minSize: 1GB
  maxSize: 10GB
```

I am able to find some config to put to my talhelper config file but not everything (like image cache feature, extramounts, registries, etc ...). Is there a kind of 'dynamic' patch that works for any `MachineConfig` parameters that aren't supported directly by TalHelper?

Thanks again for your work

**Comment by budimanjojo** [comment]
@marcopornic You can add those unsupported via `patches` like this:
**./talconfig.yaml**:
```yaml
patches:
  - "@./mypatch.yaml"
# or you can do it per node like this
# nodes:
#   - patches:
#       - "@./mypatch.yaml"
``` 
**./mypatch.yaml**:
```yaml
cluster:
  allowSchedulingOnControlPlanes: true
  apiServer:
    admissionControl:
      - name: PodSecurity # Name is the name of the admission controller.
        configuration:
          exemptions:
            namespaces:
              - metallb-system
              - local-path-storage
              - traefik
              - haproxy
              - longhorn-system
              - postgresql
              - kubernetes-dashboard
  discovery:
    enabled: false
machine:
  install:
    image: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245:v1.9.5
  sysctls:
    vm.nr_hugepages: "1024"
  kernel:
    modules:
      - name: nvme_tcp
      - name: vfio_pci
      - name: uio_pci_generic
  registries:
    mirrors:
      "127.0.0.1:31998":
        endpoints:
          - http://10.10.205.14:31998
      "127.0.0.1:31999":
        endpoints:
          - http://10.10.205.14:31999

  features:
    imageCache:
      localEnabled: true
  time:
    disabled: true
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/local-path-provisioner
        type: bind
        source: /var/local-path-provisioner
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  files:
    - content: |
        [metrics]
          address = "0.0.0.0:11234"
      path: /etc/cri/conf.d/20-customization.part
      op: create
```

`patches` can be a list of either RFC6902 or inline yaml patch or a list of filenames (with "@" prepended) that contains either RFC6902 or inline yaml patch.

I'm not sure what you mean by dynamic patch, but you can have different patches for all nodes, patches for node type, or individual node.
