### ISSUE TITLE
Endpoint not correctly generated

### ISSUE THREAD

**Issue by soulwhisper** [budimanjojo/talhelper#1019]
For a config like [this](https://github.com/soulwhisper/homelab-ops/blob/main/infrastructure/talos/talconfig.test.yaml). The generated talosconfig will  use 3 controlplane IP as endpoint.

Latest talos will report a cert error, indicate the cert is for `controlplane-hostname, controlplane-fqdn, endpoint-fqdn, talos, talos.default` but not for IP.

Suggest fix could be using configEndpoint as generatedEndpoint, or add controlplaneIP into additionalCertSans.

**Comment by soulwhisper** [comment]
Actually I dont know why it is broken. I updated tools then new cluster tests suddenly failed.

Generate clusterconfig from above `talconfig` then apply and boostrap. Before bootstrap, the talosctl will report
```shell
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for exarch-03, exarch-03.homelab.internal, k8s.homelab.internal, talos, talos.default, not 172.19.82.101:50000,172.19.82.102:50000,172.19.82.103:50000"
```
talosconfig generated looks like
```yaml
context: main
contexts:
    main:
        endpoints:
            - 172.19.82.101
            - 172.19.82.102
            - 172.19.82.103
        nodes:
            - 172.19.82.101
            - 172.19.82.102
            - 172.19.82.103
       ca: <reducted>
       crt: <reducted>
       key: <reducted>
```
replace endpoints with `k8s.homelab.internal`, it is all good again. This domain points to just the same IPs.
