### ISSUE TITLE
Use go templates for ExtensionServiceConfig

### ISSUE THREAD

**Issue by maxpain** [budimanjojo/talhelper#1045]
Hello. Is it possible to have `ExtensionServiceConfig` config file content as a separate template so that I can use some variables there?

```yaml
nodes:
  - hostname: kmaster1
    extensionServices:
      - name: nut-client
        configFiles:
          - content: MONITOR upsmonHost 1 remote pass password
            mountPath: /usr/local/etc/nut/upsmon.conf
        environment:
          - UPS_NAME=up
```

**Comment by budimanjojo** [comment]
Hi, @maxpain!

Currently you can't have `extensionServices` as a separate file. But you don't need separate file to have envsubst?
Something like so works if you define the variable inside `talenv.yaml` file:
```yaml
nodes:
  - extentionServices:
      - name: nut-client
        configFiles:
          - content: MONITOR ${myVar} 1 remote pass password
            mountPath: /usr/local/etc/nut/upsmon.conf
```

If you really need a separate file and templating, you can use `extraManifests` instead like so:
```yaml
# talconfig.yaml
nodes:
  - extraManifests:
      - ./extensionfile.yaml
    patches:
      - |-
        - op: add
          path: /machine/env
          value:
            myVar: myvalue
```

```yaml
# extensionfile.yaml
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: nut-client 
configFiles:
    - content: MONITOR {{ .MachineConfig.MachineEnv.myVar }} 1 remote username password
      mountPath: /usr/local/etc/nut/upsmon.conf
```
More information about templating `extraManifests`: https://budimanjojo.github.io/talhelper/latest/guides/#templating-extra-manifests.

The downside of the template inside `extraManifests` is you need to add the env variables to the node. Maybe there's something I can add to the template data like allowing environment variable defined inside `talenv.yaml`, let me know if you need that and I see what I can do.
