### ISSUE TITLE
Support for valid Subnets Config in machine Config

### ISSUE THREAD

**Issue by LaurinStreng** [budimanjojo/talhelper#1057]
When Attempting to Configure my NFS Network, which is in a 10.0.0.0/26 Subnet.
The Worker Nodes uses this IP for the Kubelet Network and set this to the internal IP on the node, not the ipAddress in the talconfig file.
So my Node is not Responding Correct when i add this network.

Talos has a Value for this: https://www.talos.dev/v1.10/introduction/prodnotes/
(validSubnets) which configures the desired route for kubelet communication.

Example Machine Configuration
---
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.33.0
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    nodeIP:
      validSubnets:
        - 172.20.4.40/26
---
Talhelper has no Option for the Configuration. Or I don't see it :D

Maybe I can make a PR to add it, but this could take a while.

**Comment by budimanjojo** [comment]
Thanks for the feature request!

There are actually a lot of configurations that Talhelper doesn't currently support.
For machine configuration that's not supported you can use `patches` like so:
```yaml
controlPlane:
  patches:
    - |- # example inline patch
      machine:
        kubelet:
          nodeIP:
            validSubnets:
              - 172.20.4.40/26
     - |- # example json6902 patch
       - op: add
         path: /machine/kubelet/nodeIP
         value:
           validSubnets:
             - 172.20.4.40/26
```

I'm glad that you're willing to contribute a PR, but I don't think creating a field inside `talconfig.yaml` for this is a good idea because this is not a common configuration that people would want to configure. If you really think this is needed we should have a field to configure `machine.kubelet` in general instead of just the nodeIP. Or maybe I miss something?
