### ISSUE TITLE
Config leaks between nodes

### ISSUE THREAD

**Issue by MrMarble** [budimanjojo/talhelper#152]
Hi! I noticed that the node attribute `MachineDisks` was applying to nodes that didn't have it configured.

You can test it on the example provided in the repo running `go run ./main.go genconfig -c ./example/talconfig.yaml -o ./example/clusterconfig`

```yaml
# home-cluster-kworker1.yaml
  disks:
    - device: /dev/disk/by-id/ata-CT500MX500SSD1_2149E5EC1D9D
      partitions:
        - mountpoint: /var/mnt/sata
```

Looking at the code, I think this is the problem, `nodeInput` is reused while iterating over nodes so anything that overrides the config conditionally keeps the old value:
https://github.com/budimanjojo/talhelper/blob/42f9640d812bfbec046c445188db0748227c3d72/pkg/talos/nodeconfig.go#L84-L90
