### ISSUE TITLE
Prepare for the deprecation of system extensions through config file

### ISSUE THREAD

**Issue by budimanjojo** [budimanjojo/talhelper#185]
With the [deprecation of installing system extensions through config file](https://www.talos.dev/v1.5/talos-guides/configuration/system-extensions/#installing-system-extensions), I made a change (the easiest way to get it done) by allowing per node installer image with `nodes[].talosImageURL` (https://github.com/budimanjojo/talhelper/commit/6c098210bc457eeb6a66df757d41a1acd43a4ef7).

But I think I should prepare for Talos `v1.6` which will highly likely to remove `machine.install.extensions` completely and have everybody using their [image-factory](https://factory.talos.dev) to generate installer url (I need to confirm with people from Talos to make sure).

My current thought is to change the default installer image url from `ghcr.io/siderolabs/installer` to `factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba` where the hash id is coming from the `customization` that we give it. I will add `nodes[].schematic.customization` so you can do something like this:
```yaml
nodes:
  - hostname: node1
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
```
and the generated manifest will have `machine.install.image` value to be `factory.talos.dev/installer/9e8cc193609699825d61c039c7738d81cf29c7b20f2a91d8f5c540511b9ea0b4:v1.5.4`.

You can still provide `nodes[].talosImageURL` to override it with your own image in case you don't want to use the image-factory or you build your own image.

This will also mean that providing `nodes[].extensions` will be ignored so this will be a **breaking change**, I'll make this verbose when the program detects it.

Please provide your feedback below before I start working on this.

Update: I decided to not ignore `nodes[].extensions` yet so this is **not a breaking change**. But the program will show a warning if it's being used.
