### ISSUE TITLE
missing core components

### ISSUE THREAD

**Issue by soulwhisper** [budimanjojo/talhelper#198]
Currently, the talhelper generated config do not contain controller-manager and scheduler images, talhelper show certain configs as "{}". And I could not patch it.

You can re-produce this issue by generate default config using talosctl and talhelper.

**Comment by budimanjojo** [comment]
Thanks for the issue!

You need to put `kubernetesVersion` field in `talconfig.yaml` to have it generated for you. Because without specifying it, it will default to whatever the default is with the Talos version you're using.

**Comment by budimanjojo** [comment]
Just tested it. If I put `kubernetesVersion: v1.27.0` in `talconfig.yaml`, the generated config will have:
```yaml
cluster:
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.27.0
  proxy:
    image: registry.k8s.io/kube-proxy:v1.27.0
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.27.0
```
Is this solution acceptable? There's also a validation in the code that will make sure the `kubernetesVersion` you provide is compatible with the Talos version the config will be generated with.
