### ISSUE TITLE
Generate per node factory url for `genurl` commands

### ISSUE THREAD

**Issue by budimanjojo** [budimanjojo/talhelper#211]
Right now, `talhelper genurl iso` and `talhelper genurl installer` doesn't actually generate the url based on what you put in `talconfig.yaml` file. It makes more sense if the generated urls can be taken from config file. Let's say I have this block inside my `talconfig.yaml`:
```yaml
talosVersion: v1.5.5
nodes:
  - hostname: machine1
    schematic:
       customization:
         extraKernelArgs:
           - net.ifnames=0
         systemExtensions:
           officialExtensions:
             - siderolabs/intel-ucode
             - siderolabs/tailscale
  - hostname: machine2
```
And when I run `talhelper genurl installer` from a path where the `talconfig.yaml` is found, it should return something like this:
```
machine1: factory.talos.dev/installer/e019fb5f6bf0a685e805a1263323cf8c38feefdc5a4cecbefbd5ba58e4383a62:v1.5.5
machine2: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.5.5
```

But, when I run the `talhelper genurl installer` where there's no `talconfig.yaml` found, it shouldn't error out. Instead return something like this:
```
factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.5.5
```

This change will affect `--extension` and `--kernel-args` flags to be ignored when `talconfig.yaml` is found because you want to use the ones defined in the config file instead.

This will make upgrading Talos using `talosctl upgrade` so much easier, i.e you want to update machine1, you will run: 
```
talosctl upgrade -n <machine1> --image factory.talos.dev/installer/e019fb5f6bf0a685e805a1263323cf8c38feefdc5a4cecbefbd5ba58e4383a62:v1.5.5
```
where the `--image` is gotten from the `talhelper genurl installer` command above.
