### ISSUE TITLE
Simplify applying the generated configuration

### ISSUE THREAD

**Issue by mirceanton** [budimanjojo/talhelper#214]
Currently, the workflow to bootstrap a Talos cluster using `talhelper` is to generate the per-node configuration files using `talhlper genconfig` and then manually writing the `talosctl apply` commands, pointing it to the right config file and the right node.

Given that the `talconfig.yaml` already contains all the required information in order to apply the config as well, I think that `talhelper` should have a subcommand which simplifies this process.

This could either be a command that runs the `talosctl apply` under the hood or a command that generates the `talosctl apply` command so we can pipe it into bash.

Based on the discussions in issue #211 and in the k8s@home discord, we decided that if this is to be implemented, it will most likely be the 2nd option, allowing us to pipe said output.

Expected workflow:

With the following `talconfig.yaml`:

```yaml
---
clusterName: home-cluster
talosVersion: v1.5.5
kubernetesVersion: v1.28.2
nodes:
  - hostname: cp-01.dev.k8s.mirceanton.com
    controlPlane: true
    ipAddress: 10.0.10
```

I should be able to do something along the lines of:

```bash
root@devbox:/workspace# talhelper gencommand --apply
talosctl apply-config --talosconfig ./clusterconfig/talosconfig --nodes 10.0.10.195 --file ./clusterconfig/home-cluster-cp-01.dev.k8s.mirceanton.com.yaml --insecure;
```

Thus allowing me to do something like this to bootstrap my cluster:

```bash
talhelper genconfig;
talhelper gencommand --apply | bash
```

For a single node this may seem trivial, but for clusters with multiple nodes, it easily becomes a quality of life improvement!
