### ISSUE TITLE
[feat] add talosctl health to gencommand

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#226]
talosctl health has a quite specific syntaxsis, requiring workers and controlplane nodes to be specified seperatly.

This is a great oppertunity for deploying talhelper gencommand in my honest opinion!

**Comment by budimanjojo** [comment]
What do u mean by "has a quite specific syntax"? I don't see that it's very complicated to needing to generate a command for. Can u explain the use case? I don't want to support generating all `talosctl` commands.

**Comment by mirceanton** [comment]
@Ornias1993 personally, I think that `talhelper` should really only focus on 2 kinds of commands:

- commands that need to specify the generated YAML files (such as `talosctl apply`) -> since `talhelper` generates it based on data in the `talconfig.yaml`
- commands that need to specify the installer image (such as `talosctl upgrade`) -> since `talhelper` generates the hash based on data in the `talconfig.yaml`

Other commands, such as `talosctl health` (and I also proposed not too long ago `talosctl reset` and `talosctl reboot`) have no `talhelper` specificity other than the nodes being listed in the `talconfig`.

While it would be convenient to have those, I think they fall outside of the intended scope of this tool, as it would become, more or less, a `talosctl` replacement.

---

What I did to work around some of these "limtation" is to automate these commands using a `Taskfile` and parsing the `talconfig` to extract some information, similar to this:

```yaml
# Taskfile.yaml
---
version: '3'

env:
  HOME_CLUSTER_NAME:
    sh: |-
      awk -F': ' '/clusterName/{print $2}' {{.ROOT_DIR}}/infra/home-cluster/talenv.yaml
  HOME_CLUSTER_ENDPOINT_IP:
    sh: |-
      awk -F': ' '/clusterEndpointIP/{print $2}' {{.ROOT_DIR}}/infra/home-cluster/talenv.yaml
  HOME_CLUSTER_NODES:
    sh: |-
      grep -oP 'ipAddress: \K[0-9.]+' {{.ROOT_DIR}}/infra/home-cluster/talconfig.yaml | tr '\n' ' '
      
tasks:
  ...
```
