### ISSUE TITLE
Add schematic `extraKernelArgs` into `machine.install.extraKernelArgs` automatically

### ISSUE THREAD

**Issue by budimanjojo** [budimanjojo/talhelper#243]
Right now, the `extraKernelArgs` added into `schematic` is not being respected if you apply the configuration to your existing cluster. See https://github.com/siderolabs/talos/issues/8008 for more information.

I think it makes sense for `talhelper` to add `schematic.customization.extraKernelArgs` to `machine.install.extraKernelArgs` automatically so the kernel arguments are being applied to the machine because you should always expect them to be there if you define them in your `talconfig.yaml`.
But there's a small problem because you might already have a patch like this in your `talconfig.yaml`:

```yaml
nodes:
  - hostname: host1
    ipAddress: 1.2.3.4
    patches:
      - op: add
        path: /machine/install/extraKernelArgs
        value:
          - talos.logging.kernel=udp://1.2.3.4:1234
```

And this will make the list become overwritten.
This makes this not consistent but it's what it's I think.
