### ISSUE TITLE
talosctl genconfig complains that amdgpu-firmware is not a supported talos extension

### ISSUE THREAD

**Issue by dmfrey** [budimanjojo/talhelper#258]
Defined `amdgpu-firmware` in my schematic extension block:

```
schematic: &schematic
  customization:
    systemExtensions:
      officialExtensions:
        - siderolabs/amdgpu-firmware
```
When `talosctl genconfig` is executed, the following error is displayed:
```
There are issues with your talhelper config file:
field: "nodes[0].schematic"
  * "siderolabs/amdgpu-firmware" is not a supported Talos extension
```
It is listed under `Firmware` in the `Extension Catalog`
https://github.com/siderolabs/extensions
