### ISSUE TITLE
Support for Ingress Firewall (extra configs)

### ISSUE THREAD

**Issue by vladimirfx** [budimanjojo/talhelper#284]
Please add support for extra document machine config.

https://www.talos.dev/v1.6/talos-guides/network/ingress-firewall/

**Comment by budimanjojo** [comment]
Thanks for the feature request! I'm not sure how to support this in a nice way. Do you have any idea on how this should be implemented? Should they be in the same yaml file as the machine config? How should the talconfig.yaml file looks like?

**Comment by budimanjojo** [comment]
My imagination is to have per node configuration like this:
```yaml
nodes:
  - firewallSpec:
      ingress:
        defaultAction: block
        rules:
          - name: kubelet-ingress
            portSelector:
              ports:
                - 10250
              protocol: tcp
            ingress:
              - subnet: 172.20.0.0/24
                except: 172.20.0.1/32
```
And that will create a file inside `./clusterconfig/<clustername>-<nodename>-firewall.yaml` with a content like this:
```yaml
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
  ports:
    - 10250
  protocol: tcp
ingress:
  - subnet: 172.20.0.0/24
    except: 172.20.0.1/32
```

Is this the desired implementation?

**Comment by vladimirfx** [comment]
Maybe add it as an attribute to existing node config:

```yaml
nodes:
  - hostname: master
    controlPlane: true
    ...
    firewall: 
```

And render to multi-document YAML with a `---` separator. This greatly simplifies config the application.

**Comment by budimanjojo** [comment]
@vladimirfx should the process of applying the file using `talosctl apply-config -f <filename>` on both during bootstrapping and updating works fine if the file is merged with `---` separator?
I personally don't use firewall rules for my cluster so I really don't know and I just tried to apply a `NetworkDefaultActionConfig` to one of my node and it died instantly T.T

**Comment by budimanjojo** [comment]
Turns out applying the config using `talosctl apply-config -f <filename>` wiped my entire installation. I really don't know what happened.

**Comment by aivanov-citc** [comment]
Hello.
When using talosctl, all node and firewall settings must be in one file and each node has its own firewall settings, for example
```yaml
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
  ports:
    - 10250
  protocol: tcp
ingress:
  - subnet: 172.20.0.0/24
    except: 172.20.0.1/32
---
version: v1alpha1
machine:
...
cluster:
...
```
Maybe add a separate section for extra manifests (perhaps this method applies not only firewall settings) in the node settings and include files according to the node machine configuration, for example `talconfig.yaml`
```yaml
nodes:
  - hostname: master
    controlPlane: true
    ...
    extraManifests:
      - firewall-cp.yaml
   - hostname: worker
    controlPlane: false
    ...
    extraManifests:
      - firewall-work.yaml
```
