### ISSUE TITLE
talhelper gencommand upgrade isn't SecureBoot compatible / doesn't use Schematic ID

### ISSUE THREAD

**Issue by wouterbouvy** [budimanjojo/talhelper#304]
I'm trying to upgrade my cluster to Talos 1.6.2 with talhelper 1.17
I would like to use the `talhelper gencommand upgrade` command which generates upgrades commands for standard Talos Linux iso pointing just fine.

However, I'm using different Schematic ID (97bf8e92fc6bba0f03928b859c08295d7615737b29db06a97be51dc63004e403) which refers to:

```
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ucode
```

Also I'm using SecureBoot ISO's. Which should refer to different URL to fetch from the factory:
`factory.talos.dev/installer-secureboot/97bf8e92fc6bba0f03928b859c08295d7615737b29db06a97be51dc63004e403` (installer-sercureboot instead of installer)

Is there a way to look at the `talosImageURL` referenced in the talconfig.yaml to achieve this?
