### ISSUE TITLE
Add config to disable kube-proxy

### ISSUE THREAD

**Issue by szechyjs** [budimanjojo/talhelper#391]
There isn't a way to disable kube-proxy, as doucmented in the Talos Cilium documentation.

https://www.talos.dev/v1.6/kubernetes-guides/network/deploying-cilium/#machine-config-preparation

```yml
cluster:
  network:
    cni:
      name: custom
      urls:
        - https://server.yourdomain.tld/some/path/cilium.yaml
  proxy:
    disabled: true
```

**Comment by budimanjojo** [comment]
You can use `patches` like this:
```yaml
patches:
  - |-
     cluster:
       proxy:
         disabled: true
```
