### ISSUE TITLE
Read machineFiles from a local file

### ISSUE THREAD

**Issue by mrueg** [budimanjojo/talhelper#393]
It would be great if there were a similar mechanism for machineFiles similar to https://github.com/budimanjojo/talhelper/blob/bd1cceec82428771377e246614e3fa1c7e088595/pkg/patcher/patcher.go#L54 

so one could refer to an externally generates machineFile inside the talhepler config.

**Comment by budimanjojo** [comment]
Thanks for the suggestion!

I have created a PR that will do just that, I'll do more testing tomorrow and then the next release will have this feature.

**Comment by budimanjojo** [comment]
Try out the new release!

**Comment by mrueg** [comment]
Thanks a lot for the quick solution!

**Comment by budimanjojo** [comment]
Sorry, but I don't quite understand the example you show above.

**Comment by mrueg** [comment]
Sorry if I wasn't precise enough here, hope this is a better explanation:

Right now, you can point to a local file for the content, instead of inlining it.
My request was if we also additionally can point to an array of machineFiles similar to the patches.

```yaml
patches:
  - "@./my-user-patchset.yaml"
```
that contains then the patch config.

Right now for this isn't possible for machineFiles:

```yaml
machineFiles:
  - "@./machine_files/list_of_machinefiles.yaml"
```
as right now you'd need to inline the permissions, op, path etc. for a machineFile like this:

```yaml
machineFiles:
 - content: "@./tsauth.env"
   permissions: 0o644
   path: /var/etc/tailscale2/auth.env
   op: create
```

If it were additionally possible to point to a list of machineFile configs, one could do the following:

```yaml
machineFiles:
  - "@./machine_files/list_of_machinefiles.yaml"
```

list_of_machinefiles.yaml
```yaml
 - content: "@./tsauth.env"
   permissions: 0o644
   path: /var/etc/tailscale2/auth.env
   op: create
 - content: "Hello World"
   permissions: 0o644
   path: /my/other/file
   op: create
```
