### ISSUE TITLE
talhelper parsing issue for extraManifests yaml starting with ---

### ISSUE THREAD

**Issue by AjayKumar4** [budimanjojo/talhelper#497]
NodeConfigs:
    extraManifests:
        - tailscale.yaml
        
  
  tailscale.yaml
 ```
 ---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_AUTHKEY="<tailscale_key>"
 ```
 
 error message : missing kind from yaml
 talhelper version: 1.7.4

**Comment by budimanjojo** [comment]
Thanks for the report @AjayKumar4!

I just tried this and it works fine here. I think the `talconfig.yaml` you provided is wrong. It should be like this:
```yaml
nodes:
  - extraManifests:
      - tailscale.yaml
```

The `nodeConfigs` key is inline for `nodes` and `controlPlane` and `worker` struct. So you use it like this:
```yaml
nodes:
  - <everythingInsideNodeConfigsStruct>:
worker:
  <everythingInsideNodeConfigsStruct>:
controlPlane:
  <everythingInsideNodeConfigsStruct>:
```

The only downside of having `---` in the file is that the generated manifest will have double document delimiter, but it should work just fine as long as the provided file is a valid yaml formatted document.
