### ISSUE TITLE
"Watchdog timer" feature request

### ISSUE THREAD

**Issue by soulwhisper** [budimanjojo/talhelper#543]
It would be great if you could implement the watchdog timer configs in talconfig. 

Hardware watchdog timer is [new](https://www.talos.dev/v1.7/introduction/what-is-new/#hardware-watchdog-timers) in talos v1.7. [Doc](https://www.talos.dev/v1.7/reference/configuration/runtime/watchdogtimerconfig/).

**Comment by budimanjojo** [comment]
Thank you for the feature request @soulwhisper!
Talos keep adding new configs and I'm not sure if I should support them all or support those which are popular or just tell everyone to use `extraManifests` instead.

For now (workaround as I'm still considering what to do) you can use extraManifests like so:

`./watchdog-n1.yaml`
```yaml
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
timeout: 5m
```

`./talconfig.yaml`
```yaml
...
nodes:
  - hostname: n1
    extraManifests:
      - ./watchdog-n1.yaml
```
