### ISSUE TITLE
Add support for VolumeConfig

### ISSUE THREAD

**Issue by babariviere** [budimanjojo/talhelper#626]
Talos has recently introduced a new document called [VolumeConfig](https://www.talos.dev/v1.8/talos-guides/configuration/disk-management/#machine-configuration).
Would be nice to be able to add this document when generating config.

I have tried to include file using `patches` directive, but that's just skipping the file.
`talosctl gen config --config-patch @volumeconfig.yaml` will just append the document at the end of the generated config like this:

```yaml
# talos config here...
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL # Name of the volume.
# The provisioning describes how the volume is provisioned.
provisioning:
    # The disk selector expression.
    diskSelector:
        match: system_disk # The Common Expression Language (CEL) expression to match the disk.
    grow: false # Should the volume grow to the size of the disk (if possible).
    minSize: 2GB # The minimum size of the volume.
    maxSize: 40GB # The maximum size of the volume, if not specified the volume can grow to the size of the
```

**Comment by budimanjojo** [comment]
Thank you! For now, you can use `extraManifests` like so:
```yaml
nodes:
  - extraManifests:
      - volumeconfig.yaml
 ```
And put the `volumeconfig.yaml` file in the directory of your `talconfig.yaml`.

As for native support of the `Volumeconfig` kind, I need to think whether or not to include it because Talos keep adding new kind and I don't really want to keep adding them and have too many keys that can confuse users.
