### ISSUE TITLE
Feature Request: Allow for additional data in talsecret.

### ISSUE THREAD

**Issue by justSem** [budimanjojo/talhelper#630]
I came across a particular setup that required Wireguard encryption between nodes.
During the setup I ran into the fact that it doesn't seem possible to add additional information into `talhelper.sops.yaml`, like so:

```yaml
nodes:
    - hostname: talc01
      networkInterfaces:
        - interface: eth0
          wireguard:
            privateKey: <private key>
```

I was hoping that additional data would automatically merge into the `talconfig.yaml` file. But that doesn't seem to be the case.

Right now I built a workaround with some custom SOPS rules, but I was wondering if this is somehow supported in Talhelper?
