### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Sapp00** [budimanjojo/talhelper#653]
Hi,

I am facing the error "mapping values are not allowed in this context" when parsing my talconfig. 

The respective block is the following:
```
---
clusterName: ${clusterEndpointName}
talosVersion: v1.7.6
kubernetesVersion: v1.30.3
# endpoint: https://${clusterEndpointName}.${domainName}:6443
endpoint: https://10.10.10.11:6443
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.242.0.0/16
cniConfig:
  name: none
allowSchedulingOnControlPlanes: false

nodes:
  - hostname: k8s-control01.${domainName}
    ipAddress: 10.10.10.11
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - ${nameServer}
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 10.10.10.10
  - hostname: k8s-control02.${domainName}
    ipAddress: 10.10.10.12
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - ${nameServer} # <--- line 36
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: true

controlplane:
  patches:
    [....]
    - |-
      - op: replace
        path: /cluster/etcd/ca
        value:
          crt: ${etcdCACert}
          key: ${etcdCAKey}
    [....]
```

I have no clue where this error is coming from, before reworking my configs, it was "working". Working means, that it did not throw an error, but somehow the configs were just the basic configs without my customization.

**Comment by Sapp00** [comment]
I could track it down and the error message appears because of malformed patches, which is not really intuitive.

This is the error causing patch:
```
    - |-
      - op: replace
        path: /cluster/etcd/ca
        value:
          crt: ${etcdCACert}
          key: ${etcdCAKey}
```
any idea what is wrong with it?

**Comment by budimanjojo** [comment]
Thanks for the report!

I just tried the `talconfig.yaml` you provided above (with the ${} replaced) and `talhelper genconfig` ran fine. I think the error message is you have wrong kind of value in your `talenv.yaml` file? Make sure they are in `key: value` format, for example yours should look somethine like this:
```yaml
clusterEndpointName: clustername
domainName: domainname
nameServer: 1.2.3.4
etcdCACert: LS0tLS1CRUdblbalbalballaba
etcdCAKey: LS0tLS1CRUdblbalbalballaba
```

Another one is there's no `controlplane` key, it should be `controlPlane`.
