### ISSUE TITLE
failed to generate talos config: missing kind

### ISSUE THREAD

**Issue by mdallaire** [budimanjojo/talhelper#68]
I am reorganizing my talhelper configs by splitting up patches in their dedicated files to be called from the main files but I am getting the following error: `failed to generate talos config: missing kind`

There is no new configuration done, just moving existing patches to files.

talconfig.yaml
```
...
  - hostname: k8s-05
    ipAddress: 10.0.20.205
    controlPlane: false
    installDisk: /dev/nvme0n1
    nameservers:
      - 10.0.20.1
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        addresses:
          - 10.0.20.205/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.20.1
    patches:
      - |-
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - nomodeset
        - "@./intel-ucode-patch.yaml"
...
```
intel-ucode-patch.yaml
```
- op: add
  path: /machine/install/extensions
  value:
    - image: ghcr.io/siderolabs/intel-ucode:20221108
```
