### ISSUE TITLE
How to generate multi-doc machine configs?

### ISSUE THREAD

**Issue by attilaolah** [budimanjojo/talhelper#687]
I'm trying to pass a `WatchdogTimerConfig` to my nodes. A simple way to do this is to provide a machine config with more than one document, like so:

```yaml
---
version: v1alpha1
persist: true
machine: …
cluster: …
---
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
```

However, I can't seem to figure out how to generate such a config with talhelper, all I can do is post-process the files.

Given that newer Talos versions seem to be introducing more such config types, would it make sense to somehow allow extending the generated configs in such a way?

**Comment by budimanjojo** [comment]
Do something like this:

**talconfig.yaml**
```yaml
nodes:
  - extraManifests:
      - ./watchdogtimer.yaml
# or to add it to all CP nodes or worker nodes
controlPlane:
  extraManifests:
    - ./watchdogtimer.yaml
worker:
  extraManifests:
    - ./watchdogtimer.yaml
```

**watchdogtimer.yaml**
```yaml
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
```
