### ISSUE TITLE
Whats the best way to configure disk encryption configs?

### ISSUE THREAD

**Issue by frzifus** [budimanjojo/talhelper#713]
Is there a possibility to install patches to configure [v1alpha1.SystemDiskEncryptionConfig](https://www.talos.dev/v1.8/reference/configuration/v1alpha1/config/#Config.machine.systemDiskEncryption) [[offical docs](https://www.talos.dev/v1.8/talos-guides/configuration/disk-encryption/)]?

---
**update**

Oh apparently there is a patch field :)
```yaml
nodes:
  - hostname: master1
    ipAddress: 192.168.5.2
    installDisk: /dev/sda
    controlPlane: true
    patches:
      - |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - static:
                    passphrase: ${diskEncryption}
                    slot: 0
```

**Comment by frzifus** [comment]
mh... Seems there is a check preventing me from patching the `machine` entry?
```bash
2024/11/17 21:30:20 failed to generate talos config: unknown keys found during decoding:
machine:
    systemDiskEncryption:
        state:
            keys:
                - static:
                    slot: 0
```

**Comment by frzifus** [comment]
Sorry for the noise. I messed up with the formatting. :face_exhaling: 

That one works..
```yaml
patches:
  - |-
    machine:
      systemDiskEncryption:
        state:
          provider: luks2
          keys:
            - static:
                passphrase: ${diskEncryption}
              slot: 0
```
