### ISSUE TITLE
Creating bonded interface does not appropriately set interfaces or xmitHashPolicy

### ISSUE THREAD

**Issue by wrmedford** [budimanjojo/talhelper#831]
Example talconfig.yaml snippet:

```
      - interface: bond1
        addresses:
          - 192.168.68.111
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        mtu: 9000
        bond:
          mode: 802.3ad
          miimon: 100
          xmit_hash_policy: layer2+3
          updelay: 200
          downdelay: 200
          lacp_rate: fast
          slaves:
            - eth2
            - eth3 
```
Example output:
```
      - interface: bond1
        addresses:
          - 192.168.68.111
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        bond:
          interfaces: []
          mode: 802.3ad
          miimon: 100
          updelay: 200
          downdelay: 200
        mtu: 9000
```
Expected output:
```
      - interface: bond1
        addresses:
          - 192.168.68.111
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.68.1
        bond:
          interfaces: 
            - eth2
            - eth3
          xmitHashPolicy: layer2+3
          mode: 802.3ad
          miimon: 100
          updelay: 200
          downdelay: 200
        mtu: 9000
```
