### ISSUE TITLE
Impossible to use cilium as inlineManifest

### ISSUE THREAD

**Issue by lehmanju** [budimanjojo/talhelper#833]
Tried using following snippet in `talconfig.yaml` with a cilium config generated by `helm template`:

````
...
patches:
  - op: add
    path: /cluster/inlineManifests
    value:
      - name: cilium
        contents: |
          ---
          # Source: cilium/templates/cilium-secrets-namespace.yaml
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "cilium-secrets"
          ---
         ....
````

I get following error: `failed to generate talos config: variable ${host} not set`.

This is because the cilium config contains this following snippet:

````
---
# Source: cilium/templates/hubble-ui/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-ui-nginx
  namespace: kube-system
data:
  nginx.conf: "server {\n    listen       8081;\n    listen       [::]:8081;\n    server_name  localhost;\n    root /app;\n    index index.html;\n    client_max_body_size 1G;\n\n    location / {\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n\n        # CORS\n        add_header Access-Control-Allow-Methods \"GET, POST, PUT, HEAD, DELETE, OPTIONS\";\n        add_header Access-Control-Allow-Origin *;\n        add_header Access-Control-Max-Age 1728000;\n        add_header Access-Control-Expose-Headers content-length,grpc-status,grpc-message;\n        add_header Access-Control-Allow-Headers range,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout;\n        if ($request_method = OPTIONS) {\n            return 204;\n        }\n        # /CORS\n\n        location /api {\n            proxy_http_version 1.1;\n            proxy_pass_request_headers on;\n            proxy_hide_header Access-Control-Allow-Origin;\n            proxy_pass http://127.0.0.1:8090;\n        }\n        location / {\n            # double `/index.html` is required here \n            try_files $uri $uri/ /index.html /index.html;\n        }\n\n        # Liveness probe\n        location /healthz {\n            access_log off;\n            add_header Content-Type text/plain;\n            return 200 'ok';\n        }\n    }\n}"
---
````

`nginx.conf` contains the string `$host` which is interpreted as variable by talhelper.

**Comment by budimanjojo** [comment]
@lehmanju Thanks for reporting!

You're correct, currently there's no way to handle this. Do you have any suggestion on how to fix this problem?
I'll just installl cilium using other method but I also want to have this problem gone. The technical problem is that the first thing `talhelper` do is to do envsubst to the entire `talconfig.yaml` file before doing anything so it can't continue if the variable is not set.

Another ugly but works hack is to have something like this in your `talenv.yaml` file:
```yaml
host: $host
remote_addr: $remote_addr
request_method: $request_method
uri: $uri
```

**Comment by lehmanju** [comment]
I think, it would be cool to not have to include the whole helm template as string into yaml but to read it from a file. So you would write something like this:

````
patches:
  - op: add
    path: /cluster/inlineManifests
    value:
      - name: cilium
        contents: !include cilium.yaml
````

Then the convention would just be that variables are not substituted in included files.
