### ISSUE TITLE
cannot use $patch: delete for machine patches

### ISSUE THREAD

**Issue by clementnuss** [budimanjojo/talhelper#876]
hi, 

I'm trying to remove the `exclude-from-load-balancer` label from my control-plane nodes, but am getting an error:

patch:
```yaml
controlPlane:
  patches:
    - |-
      machine:
        nodeLabels:
          node.kubernetes.io/exclude-from-external-load-balancers:
            $patch: delete
```

error:
```shell
2025/03/03 07:01:06 failed to parse config file: failed to substitute env: variable ${patch} not set
```

is there any way to add a `skipEnvSubst` arg somehow ?

**Comment by budimanjojo** [comment]
Hi!

You're using `patches` wrong. It should be something like this:
```yaml
controlPlane:
  patches:
    - |-
       - op: remove
         path: /machine/nodeLabels/node.kubernetes.io~1exclude-from-external-load-balancers
         value: the-value
```

But then, I think it's not there by default so it means you added it, why not just don't add it? Sorry if I misunderstood you, I'm really confused here.

**Comment by clementnuss** [comment]
hi @budimanjojo,

thanks a lot for your prompt reply! I managed to remove those labels with the following:
```yaml
  patches:
    - |-
      - op: remove
        path: /machine/nodeLabels/node.kubernetes.io~1exclude-from-external-load-balancers
```

Talos automatically adds those labels since a few version if I'm right, but your patch does offer the possibility to remove the labels for cases like mine where my control-plane nodes also run workloads.

thanks a lot for the help and for talhelper, it's really great 👍🏼 👏🏼
