### ISSUE TITLE
VIP possible ?

### ISSUE THREAD

**Issue by jakoberpf** [budimanjojo/talhelper#94]
Heylo, just found this awesome tool and wanted to test this on one of my clusters, but I am failing to apply a VIP configuration with the custom patch method:

```bash
talhelper genconfig
2023/02/26 03:51:13 failed to generate talos config: unknown keys found during decoding:
machine:
    network:
        vip:
            ip: 192.168.1.10
```

with a config of

```yaml
clusterName: artemis
talosVersion: v1.3.5
kubernetesVersion: v1.26.0
endpoint: https://192.168.1.10:6443
domain: artemis.local
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - 192.168.1.10
additionalApiServerCertSans:
  - artemis.local
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
nodes:
  - hostname: master1
    ipAddress: 192.168.1.11
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.1.11/16
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.178.1
        mtu: 1500
        dhcp: true
  - hostname: master2
    ipAddress: 192.168.1.12
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.1.12/16
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.178.1
        mtu: 1500
        dhcp: true
  - hostname: master3
    ipAddress: 192.168.1.13
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.1.13/16
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.178.1
        mtu: 1500
        dhcp: true
controlPlane:
  patches:
    - |-
      - op: add
        path: /machine/network/vip
        value:
          ip: 192.168.1.10
```

I thinks its just the validation library which is complaining and/or is missing this feature? Didn't really investigate yet. If I have any obvious errors please let me know :-)

**Comment by budimanjojo** [comment]
Thanks!
To use VIP, you can just put it in the `nodes[].networkInterfaces[].vip` like this:
```
nodes:
  - hostname: master1
    ipAddress: 192.168.1.11
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.1.11/16
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.178.1
        mtu: 1500
        dhcp: true
        vip:                  <<<<<<
          ip: 192.168.1.10    <<<<<<
```
It can't be patched because it is a list. The path should be `/machine.network.interfaces[0].vip.ip`
