### ISSUE TITLE
Support for EthernetConfig patches in node configuration

### ISSUE THREAD

**Issue by vrozaksen** [budimanjojo/talhelper#974]
When attempting to apply `EthernetConfig` patches for network interface tuning (e.g., ring buffer adjustments), the configuration does not seem to be injected into the final Talos node config.  

#### **Example Patch**:  
```yaml
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp1s0f0np0
rings:
    rx: 4096
    tx: 4096
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp1s0f1np1
rings:
    rx: 4096
    tx: 4096
```  

#### **Expected Behavior**  
The `EthernetConfig` settings should be included in the generated node configuration (similar to how manually appending them to `main-$NODE.yaml` works).  

#### **Observed Behavior**  
- The patch does **not** appear in the final Talos config.  
- Manually adding these blocks to `main-$NODE.yaml` works correctly, confirming that the syntax itself is valid.  

#### **Question**  
Is this a limitation in `talhelper`'s patch system, or am I applying the patch incorrectly? If unsupported, could `EthernetConfig` patching be added?  

---  

### **Additional Notes**  
- If there’s a workaround (e.g., a different patch format), clarification would be appreciated.  
- This is particularly useful for performance tuning (e.g., disabling offloads, adjusting ring buffers).
