### ISSUE TITLE
Missing kind on patch to controlPlane

### ISSUE THREAD

**Issue by TheSirC** [budimanjojo/talhelper#998]
Thank you a lot for your work on talhelper !

I am wondering why I am getting the following error : `failed to generate talos config: missing kind` with the follwoing configuration files 

```yaml
# talconfig.yaml
# rest of the config that I know "compile" correctly [...]
controlPlane:
  patches:
    - "@./patches/control-plane-network-rules.yml"
```

```yaml
# ./patches/control-plane-network-rules.yml
controlPlane:
  ingressFirewall:
      defaultAction: "block"
      rules:
        - name: "kubelet-ingress"
          portSelector:
            ports:
              - 10250
            protocol: "tcp"
          ingress:
            - subnet: "10.14.0.0/16"
        - name: "apid-ingress"
          portSelector:
            ports:
              - 50000
            protocol: "tcp"
          ingress: &everywhere
            - subnet: "0.0.0.0/0"
            - subnet: "::/0"
        - name: "trustd-ingress"
          portSelector:
            ports:
              - 50001
            protocol: "tcp"
          ingress:
            - subnet: "10.14.0.0/16"
        - name: "kubernetes-api-ingress"
          portSelector:
            ports:
              - 6443
            protocol: "tcp"
          ingress: *everywhere
        - name: "etcd-ingress"
          portSelector:
            ports:
              - "2379-2380"
            protocol: "tcp"
          ingress:
            - subnet: "192.168.1.100/32"

```

I know that including the file contents directly in `talconfig.yaml` works but my understanding does not allow me to understand why the patch inclusion does not work. I know that the problem is on my side but I am trying to understand why.

**Comment by budimanjojo** [comment]
Thank you!

I think you misunderstood what `patches` are for. They should be list of patches that should be applied to the manifests after they're being generated and not patches of Talhelper configuration.

For your use case, you don't need to use patches, instead you can just put these lines inside `talconfig.yaml` file (which I think based on your comment above you already aware of):
```yaml
controlPlane:
  ingressFirewall:
    .....
```

if you really need to have them in another file, you can use `extraManifests` instead because they're different manifests and need to be put in another yaml document and they can't be declared as `patches` at all. But you should put the `v1alpha1.NetworkDefaultActionConfig` and `v1alpha1.NetworkRuleConfig` documents instead of Talhelper config like so:

**./talconfig.yaml**
```yaml
controlPlane:
  extraManifests:
    - ./patches/control-plane-network-rules.yml
```
**./patches/control-plane-network-rules.yml**
```yaml
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
    ports:
        - 10250
    protocol: tcp 
ingress:
    - subnet: "10.14.0.0/16"
---
## Repeat for the others
```

Hope this answer your questions.
